baseURL = "https://andrew-steingass.github.io/resume_website/"
canonifyURLs = true ## IMPORTANT!
languageCode = 'en-us'
title = 'Andy Steingass | Developer & Architect'
theme = "resume"

[params]
  firstName = "Andrew"
  lastName = "Steingass"
  address = "Peoria, IL"
  phone = "(219) 242-2614"
  email = "AndrewSteingass@gmail.com"
  linkedin = "https://linkedin.com/in/asteingass"
  github = "https://github.com/Andrew-Steingass"
  profileImage = "images/HeadShot.jpg"
  extraInfo = "Data Engineer | Data Scientist | Data Architect | Data Analyst"
  showSkills = true
  sections = [ "experience",  "education",  "skills"]
  
[params.skill_icons]
  python = "icons/python.png"
  javascript = "icons/javascript.png"
  go = "icons/go.png"
  sql = "icons/sql.png"
  typescript = "icons/typescript.png"
  r = "icons/r.png"
  react = "icons/react.png"
  hugo = "icons/hugo.png"
  "node.js" = "icons/nodejs.png"
  powershell = "icons/powershell.png"
  json = "icons/json.png"
  postgresql = "icons/postgres.png"
  "Microsoft SQL Server" = "icons/microsoftsql.jpg"
  mysql = "icons/mysql.jpg"
  sqlite = "icons/sqlite.jpg"
  milvus = "icons/milvus.jpg"
  elasticsearch = "icons/elasticsearch.png"
  "Google Cloud Platform (GCP)" = "icons/gcp.png"
  "Microsoft Azure" = "icons/azure.jpg"
  "Box Storage" = "icons/box.png"
  docker = "icons/docker.jpg"
  "azure devops" = "icons/azuredevops.jpg"
  "restful apis" = "icons/restfulapi.png"
  "google apis" = "icons/google.jpg"
  "close.io apis" = "icons/closeio.png"
  "box apis" = "icons/box.png"
  zapier = "icons/zapier.png"
  "power bi" = "icons/powerbi.jpg"
  tableau = "icons/tableau.png"
  agile = "icons/agile.png"
  trello = "icons/trello.jpg"
  "microsoft excel" = "icons/excel.jpg"
  word = "icons/word.jpg"
  powerpoint = "icons/powerpoint.jpg"


[params.skills]
  enable = true
  title = "Skills"

[[params.skills.list]]
  title = "Programming Languages"
  description = "Python, SQL, Go, TypeScript, R, JavaScript"

[[params.skills.list]]
  title = "Web Development"
  description = "React, Hugo, Node.js"

[[params.skills.list]]
  title = "Scripting & Markup Languages"
  description = "PowerShell, JSON"

[[params.skills.list]]
  title = "Databases"
  description = "PostgreSQL, Microsoft SQL Server, MySQL, SQLite, Milvus, ElasticSearch"

[[params.skills.list]]
  title = "Cloud Platforms & Services"
  description = "Google Cloud Platform (GCP), Microsoft Azure, Box Storage"

[[params.skills.list]]
  title = "DevOps & Containerization"
  description = "Docker, Azure DevOps"

[[params.skills.list]]
  title = "APIs & Integrations"
  description = "RESTful APIs, Google APIs, Close.io APIs, Box APIs, Zapier"

[[params.skills.list]]
  title = "Business Intelligence"
  description = "Tableau, Power BI"

[[params.skills.list]]
  title = "Project Management"
  description = "Agile, Trello"

[[params.skills.list]]
  title = "Software Proficiency"
  description = "Microsoft Excel, Word, PowerPoint"

[[menu.main]]
  name = "About"
  url = "/resume_website/#about"  # Updated link for GitHub Pages
  weight = 1

[[menu.main]]
  name = "Skills"
  url = "/resume_website/#skills"  # Updated link for GitHub Pages
  weight = 2

[[menu.main]]
  name = "Experience"
  url = "/resume_website/#experience"  # Updated link for GitHub Pages
  weight = 3

[[menu.main]]
  name = "Education"
  url = "/resume_website/#education"  # Updated link for GitHub Pages
  weight = 4

[[menu.main]]
  name = "Projects"
  url = "/resume_website/#projects"  # Updated link for GitHub Pages
  weight = 5
